title: Hemesh Raaja Malathi
logo: /assets/img/headshot_image.jpeg
description: |
  <div style="text-align: center;">
    <img src="/assets/img/headshot_image.jpeg" alt="Hemesh Raaja Malathi" style="border-radius: 50%; width: 150px; height: 150px;">
    <h1>Hemesh Raaja Malathi</h1>
    <p>Compute Science Engineer</p>
    <ul style="list-style: none; padding: 0;">
      <li><a href="https://twitter.com/your_twitter_handle">Twitter</a></li>
      <li><a href="https://www.linkedin.com/in/your_linkedin_handle">LinkedIn</a></li>
      <li><a href="https://github.com/your_github_handle">GitHub</a></li>
      <li><a href="https://www.facebook.com/your_facebook_handle">Facebook</a></li>
      <li><a href="https://www.instagram.com/your_instagram_handle">Instagram</a></li>
    </ul>
  </div>
show_downloads: true
theme: jekyll-theme-minimal




